application: armory
version: 1
runtime: python27
api_version: 1
threadsafe: 1

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /
  script: home.application
- url: /user
  script: home.application
- url: /campaign
  script: home.application
- url: /stylesheets
  static_dir: stylesheets
- url: /javascript
  static_dir: javascript
- url: /images
  static_dir: images
